config/routes.rb
Certif::Application.routes.draw do
  resources :certificates
  root :to => redirect('/certificates')

end

app/models/address.rb
class Address < ActiveRecord::Base
	attr_accessible  :name1, :name2, :street1, :steet2, :postalcode, :city, :countrycode, :countryname
  belongs_to :certificate

  validates_presence_of :city
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
	attr_accessible  :Version, :ControllingInstance, :SubType,:Profile,:DocumentID,:IssueDate, :address_attributes
	has_one :address
	accepts_nested_attributes_for :address,
		:allow_destroy => true,
    	:reject_if     => :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # Configure the default encoding used in templates for Ruby 1.9. 
  config.encoding = "utf-8"
end

app/controllers/certificates_controller.rb
# This file is app/controllers/movies_controller.rb
class CertificatesController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
    @certificates = Certificate.order(sort_column + ' ' + sort_direction)
  end
  def new
    @certificate = Certificate.new
  end
  def edit
    @certificate = Certificate.find(params[:id])
  end
  def create
    @certificate = Certificate.new(params[:certificate])
    if @certificate.save
      redirect_to @certificate
    else
      render :action => 'new'
    end
  end
  def update
    @certificate = Certificate.find(params[:id])
    if @certificate.update_attributes(params[:certificate])
      redirect_to (certificates_url)
    else
      render :action => 'edit'
    end
  end
  def show
    @certificate = Certificate.find(params[:id])
    #redirect_to (certificates_url)
    binding.pry
  end
def destroy
    @certificate = Certificate.find(params[:id])
    @certificate.destroy
    redirect_to(certificates_url)
  end
  
  private
  def sort_column
    Certificate.column_names.include?(params[:sort]) ? params[:sort] : "DocumentID"   
  end
  
  def sort_direction
   %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/form_helper.rb
# app/helpers/form_helper.rb
module FormHelper
  def setup_certificate(certificate)
    certificate.address ||= Address.new
    certificate
  end
end

app/views/certificates/_form.html.erb
# app/views/certificates/_form.html.erb
<%= form_for(setup_certificate @certificate) do |f| %>
  <% if @certificate.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@certificate.errors.count, "error") %> prohibited
        this certificate from being saved:
      </h2>
      <ul>
      <% @certificate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :Version %>
    <%= f.text_field :Version %>
    <%= f.label :ControllingInstance %>
    <%= f.text_field :ControllingInstance %>  
  </div>

  <%= f.fields_for :address do |ff| %>
    <div>
      <%= ff.label :city %>
      <%= ff.text_field :city %>
      <%= ff.label :postalcode %>
      <%= ff.text_field :postalcode %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/certificates/edit.html.erb
<h1>Editing certificate</h1>

<%= render 'form' %>

<%= link_to 'Show', @certificate %> |
<%= link_to 'Back', certificates_path %>

app/views/certificates/index.html.erb
<h1>Listing certificates</h1>

<table>
  <tr>
    <th>Version</th><th>Profile</th><th>city</th>
  </tr>

<% @certificates.each do |certificate| %>
  <tr>
    <td><%=h certificate.Version %></td>
    <td><%=h certificate.Profile %></td>

    <td><%=h certificate.address.try(:city) %></td>
    <td><%= link_to 'Show', certificate %></td>
    <td><%= link_to 'Edit', edit_certificate_path(certificate) %></td>
    <td><%= link_to 'Destroy', certificate, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New certificate', new_certificate_path %>

app/views/certificates/indexv2.html.haml
-#  This file is app/views/certificates/index.html.haml
%h2 All Certificates

= form_tag certificates_path, :method => :get, :id => 'certificateslist_form' do
  -#
%table.pretty#certificates
  %thead
    %tr
      %th Version
      %th Controlling Instance
      %th SubType
      %th Profile
      %th= sortable 'DocumentID', "ID doc"
      %th= sortable "IssueDate", "Issue Date"
  %tbody
    - for certificate in @certificates
      %tr
        %td= certificate.Version 
        %td= certificate.ControllingInstance
        %td= certificate.SubType
        %td= certificate.Profile
        %td= certificate.DocumentID
        %td= certificate.IssueDate
        %td= certificate.DocumentFunctionCode
        %td= certificate.CertificateType
        %td= certificate.IdentifierAgency
        # adresse
        Name1
        Name2
        Street1
        Street2
        PostalCode
        City
        CountryCode
        CountryName
        Telephone
        Telefax
        Email
        # logo
        Logo
        # image
        

app/views/certificates/show.html.erb
<h1>Show certificate</h1>
<p>
  <b>Entete certificat:</b>
  <%=h @certificate.Version %>
  <%=h @certificate.Profile %>
  <br />
  <b>Adresse:</b>
  <%= h @certificate.address.city %>
  <%#= binding.pry %>
</p>


<%= link_to 'Edit', edit_certificate_path %> |
<%= link_to 'Back', certificates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Certif</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>